language: android
jdk: oraclejdk7


android:
  components:
    - build-tools-21.1.2
    - android-21
    - extra


script:
    # default target is "build connectedCheck" but that breaks on travis
    # because emulator is not well supported yet.
    # http://docs.travis-ci.com/user/languages/android/
    - ./gradlew build assemble
