language: android
jdk: oraclejdk7


android:
  components:
    - build-tools-21.1.0
    - android-21
    - extra

script:
    # default target is "build connectedCheck" but that breaks on travis
    # because there is no emulator
    # http://docs.travis-ci.com/user/languages/android/
    - ./gradlew build assembleDebug
