language: android
jdk: oraclejdk7


android:
  components:
    - build-tools-21.1
    - android-21
    - extra

script:
    - echo "Travis branch is $TRAVIS_BRANCH"
    - ./gradlew clean assembleDebug
